//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VacationsPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CashInAdvance
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CashInAdvance()
        {
            this.ExpensesReports = new HashSet<ExpensesReport>();
        }
    
        public int Id { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public int CurrencyID { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> ManagerApproverID { get; set; }
        public Nullable<int> OperationApproverID { get; set; }
        public string Reason { get; set; }
        public Nullable<int> TripID { get; set; }
        public Nullable<System.DateTime> RequestDate { get; set; }
        public Nullable<System.DateTime> ManagerApprovalDate { get; set; }
        public Nullable<System.DateTime> OperationApprovalDate { get; set; }
        public Nullable<int> CashInAdvanceStatus { get; set; }
        public Nullable<bool> Paid { get; set; }
        public string RejectionReason { get; set; }
        public Nullable<double> ExchangeRate { get; set; }
        public Nullable<decimal> SettledAmount { get; set; }
        public Nullable<System.DateTime> SettlementDate { get; set; }
        public string OperationsComment { get; set; }
    
        public virtual CashInAdvanceStatu CashInAdvanceStatu { get; set; }
        public virtual Currency Currency { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Trip Trip { get; set; }
        public virtual Employee Employee1 { get; set; }
        public virtual Employee Employee2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExpensesReport> ExpensesReports { get; set; }
    }
}
