//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VacationsPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.Employees1 = new HashSet<Employee>();
            this.Employees11 = new HashSet<Employee>();
            this.Employees12 = new HashSet<Employee>();
            this.EmployeesVacationDays = new HashSet<EmployeesVacationDay>();
            this.EmployeesWeekendDays = new HashSet<EmployeesWeekendDay>();
            this.VacationsHistories = new HashSet<VacationsHistory>();
            this.VacationsLogs = new HashSet<VacationsLog>();
        }
    
        public int Id { get; set; }
        public string employeeId { get; set; }
        public Nullable<System.DateTime> hiringDate { get; set; }
        public Nullable<int> directLine { get; set; }
        public Nullable<int> dottedLine { get; set; }
        public Nullable<int> RoleID { get; set; }
        public Nullable<int> Workload { get; set; }
        public Nullable<int> VacationBalance { get; set; }
        public Nullable<int> CasualLeaveBalance { get; set; }
        public Nullable<bool> Provisioned { get; set; }
        public Nullable<bool> Active { get; set; }
        public string StatusUpdates { get; set; }
        public string Location { get; set; }
        public Nullable<int> RoleTypeID { get; set; }
        public Nullable<int> FundID { get; set; }
        public Nullable<int> NumberOfCheckIns { get; set; }
        public Nullable<System.DateTime> LastCheckIn { get; set; }
        public Nullable<bool> Resigned { get; set; }
        public Nullable<System.DateTime> ResignationDate { get; set; }
        public Nullable<int> NextYearBalance { get; set; }
        public Nullable<int> NextYearCasualLeaveBalance { get; set; }
        public Nullable<int> VacationsCarryOver { get; set; }
        public Nullable<int> OriginalCarryOver { get; set; }
        public Nullable<bool> HasQuotas { get; set; }
    
        public virtual contact contact { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee> Employees1 { get; set; }
        public virtual Employee Employee1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee> Employees11 { get; set; }
        public virtual Employee Employee2 { get; set; }
        public virtual Role Role { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee> Employees12 { get; set; }
        public virtual Employee Employee3 { get; set; }
        public virtual Workload Workload1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeesVacationDay> EmployeesVacationDays { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeesWeekendDay> EmployeesWeekendDays { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VacationsHistory> VacationsHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VacationsLog> VacationsLogs { get; set; }
    }
}
