//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VacationsPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeesView
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
        public string BasedOut { get; set; }
        public string DirectLine { get; set; }
        public string DottedLine { get; set; }
        public Nullable<System.DateTime> HiringDate { get; set; }
        public Nullable<int> VacationBalance { get; set; }
        public Nullable<int> VacationsCarryOver { get; set; }
        public string PassportNumber { get; set; }
        public string Role { get; set; }
        public string Workload { get; set; }
        public Nullable<bool> Resigned { get; set; }
    }
}
