//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VacationsPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpensesReport
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ExpensesReport()
        {
            this.ExpensesDetails = new HashSet<ExpensesDetail>();
            this.CashInAdvances = new HashSet<CashInAdvance>();
        }
    
        public int ID { get; set; }
        public Nullable<System.DateTime> ApprovalDate { get; set; }
        public Nullable<double> TotalAmountInUSD { get; set; }
        public System.DateTime SubmissionDate { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<double> USDExchange { get; set; }
        public Nullable<int> TripID { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<int> ValidatorID { get; set; }
        public Nullable<int> ApproverID { get; set; }
        public Nullable<double> CashInAdvance { get; set; }
        public string ExpenseBrief { get; set; }
        public Nullable<int> StatusID { get; set; }
        public string ExceededLimitReason { get; set; }
        public string Title { get; set; }
        public Nullable<double> TotalAmountInEGP { get; set; }
        public Nullable<decimal> SettledAmount { get; set; }
        public Nullable<System.DateTime> SettlementDate { get; set; }
        public string OperationsComment { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Employee Employee1 { get; set; }
        public virtual Employee Employee2 { get; set; }
        public virtual ExpenseReportStatu ExpenseReportStatu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExpensesDetail> ExpensesDetails { get; set; }
        public virtual Trip Trip { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CashInAdvance> CashInAdvances { get; set; }
    }
}
