//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VacationsPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Route
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Route()
        {
            this.ExpensesDetails = new HashSet<ExpensesDetail>();
        }
    
        public int routeId { get; set; }
        public int tripId { get; set; }
        public Nullable<System.DateTime> arrivalDate { get; set; }
        public Nullable<int> toCountry { get; set; }
        public Nullable<int> fromCountry { get; set; }
        public Nullable<bool> requireVisa { get; set; }
        public Nullable<int> CityFrom { get; set; }
        public Nullable<int> CityTo { get; set; }
        public Nullable<int> HotelInfoId { get; set; }
        public Nullable<bool> AccommodationRequested { get; set; }
        public Nullable<bool> FlightRequested { get; set; }
        public Nullable<bool> InvitationLetterRequested { get; set; }
        public Nullable<bool> HRLetterRequested { get; set; }
        public Nullable<int> Rating { get; set; }
        public Nullable<double> VisaCost { get; set; }
        public Nullable<int> VisaCostCurrencyID { get; set; }
        public Nullable<int> VisaStatusID { get; set; }
        public Nullable<double> ForecastedFlight { get; set; }
        public Nullable<double> ForecastedAccommodation { get; set; }
        public Nullable<double> ForecastedExpenses { get; set; }
        public Nullable<double> ForecastedTotal { get; set; }
        public Nullable<int> HotelRating { get; set; }
    
        public virtual City City { get; set; }
        public virtual City City1 { get; set; }
        public virtual Country Country { get; set; }
        public virtual Country Country1 { get; set; }
        public virtual Currency Currency { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExpensesDetail> ExpensesDetails { get; set; }
        public virtual TRHotelInfo TRHotelInfo { get; set; }
        public virtual Trip Trip { get; set; }
        public virtual TRItemsStatu TRItemsStatu { get; set; }
    }
}
