//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VacationsPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRHotelInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TRHotelInfo()
        {
            this.Routes = new HashSet<Route>();
        }
    
        public int Id { get; set; }
        public Nullable<int> TRID { get; set; }
        public string CountryName { get; set; }
        public Nullable<int> HotelId { get; set; }
        public Nullable<double> HotelRate { get; set; }
        public Nullable<int> PaymentMethodID { get; set; }
        public System.DateTime CheckInDate { get; set; }
        public System.DateTime CheckOutDate { get; set; }
        public Nullable<int> CurrencyID { get; set; }
    
        public virtual Currency Currency { get; set; }
        public virtual Hotel Hotel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Route> Routes { get; set; }
        public virtual TravelRequest TravelRequest { get; set; }
    }
}
