//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VacationsPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRHotelInfoView_Archive
    {
        public int Id { get; set; }
        public Nullable<int> TRID { get; set; }
        public string Country { get; set; }
        public string Name { get; set; }
        public Nullable<double> HotelRate { get; set; }
        public string Currency { get; set; }
        public string PaymentMethod { get; set; }
        public Nullable<System.DateTime> CheckInDate { get; set; }
        public Nullable<System.DateTime> CheckOutDate { get; set; }
        public string Hotel { get; set; }
    }
}
