//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VacationsPortal.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CIDvNEXtEntities : DbContext
    {
        public CIDvNEXtEntities()
            : base("name=CIDvNEXtEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<contact> contacts { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<EmployeesVacationDay> EmployeesVacationDays { get; set; }
        public virtual DbSet<EmployeesWeekendDay> EmployeesWeekendDays { get; set; }
        public virtual DbSet<EmployeeVacation> EmployeeVacations { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Subsidary> Subsidaries { get; set; }
        public virtual DbSet<VacationBalanceBackUp> VacationBalanceBackUps { get; set; }
        public virtual DbSet<VacationsHistory> VacationsHistories { get; set; }
        public virtual DbSet<VacationsLog> VacationsLogs { get; set; }
        public virtual DbSet<VacationStatusType> VacationStatusTypes { get; set; }
        public virtual DbSet<VacationType> VacationTypes { get; set; }
        public virtual DbSet<Workload> Workloads { get; set; }
        public virtual DbSet<EmployeesView> EmployeesViews { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<AuthUser> AuthUsers { get; set; }
    }
}
