//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VacationsPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VisasView
    {
        public int Id { get; set; }
        public Nullable<int> TRID { get; set; }
        public string Employee { get; set; }
        public string Country { get; set; }
        public Nullable<double> VisaCost { get; set; }
        public string Currency { get; set; }
        public Nullable<int> RouteId { get; set; }
    }
}
