//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VacationsPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subsidary
    {
        public int Id { get; set; }
        public string SubsidaryName { get; set; }
        public string ChildSubName { get; set; }
        public Nullable<double> FlightAverage { get; set; }
    }
}
