//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VacationsPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VacationsHistory
    {
        public int Id { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public string username { get; set; }
        public Nullable<int> TypeId_ { get; set; }
        public Nullable<System.DateTime> fromdate { get; set; }
        public Nullable<System.DateTime> todate { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public byte[] attachements { get; set; }
        public string reason { get; set; }
        public Nullable<int> WorkingDays { get; set; }
        public string AttachmentName { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual VacationStatusType VacationStatusType { get; set; }
        public virtual VacationType VacationType { get; set; }
    }
}
